### DISCUSSION TITLE
Helix Editor - Volar Setup - How to?

### DISCUSSION THREAD

**Discussion by 4nd1m4n** [vuejs/language-tools#2279] [Q&A]
Hello Volar Team,

I'm currently trying out the [helix editor](https://helix-editor.com/) and i like how blazingly fast it is.

However, for now they only have vue support via vls but not volar jet.
But one can configure their own language support via just adding a few lines.

The vls-server is configured like this in a *.toml file format:
```toml
[[language]]
name = "vue"
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
roots = ["package.json", "vue.config.js"]
indent = { tab-width = 2, unit = "  " }
language-server = { command = "vls" }

[[grammar]]
name = "vue"
source = { git = "https://github.com/ikatyang/tree-sitter-vue", rev = "91fe2754796cd8fba5f229505a23fa08f3546c06" }
```

Can someone tell me how i could transform this to use volar instead?
For example [Here on Reddit](https://www.reddit.com/r/HelixEditor/comments/zyuu9z/helix_and_volar/) i read, that i at least need these two fields:
```toml
[[language]]
name = "vue"
language-server.command = "?????"
```
Of course the whole configuration would also be appreciated, but what would the `language-server.command` be?

**Comment by johnsoncodehk** [comment]
`@volar/vue-language-server` command is `vue-language-server`: https://github.com/johnsoncodehk/volar/blob/676b815e1df4e4ccf24045758b0181fa29836a2e/vue-language-tools/vue-language-server/package.json#L11

And you also needed to add `{ typescript: { tsdk: '.../node_modules/typescript/lib' } }` setting for server init options: https://github.com/neovim/nvim-lspconfig/blob/80e81b158d7dd2d4baa0384560b226d089b3a8fe/lua/lspconfig/server_configurations/volar.lua#L72-L80

**Reply by 4nd1m4n** [reply]
Thank you for your reply!

I have tried variants of this now, where i think that this would be my best try:
```toml
[[language]]
name = "vue"
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
roots = ["package.json"]
indent = { tab-width = 4, unit = "    " }
language-server = { command = "vue-language-server", args = ["--stdio"] }
config = { typescript = { tsdk = "node_modules/typescript/lib" } }
auto-format = true

[[grammar]]
name = "vue"
source = { git = "https://github.com/ikatyang/tree-sitter-vue", rev = "91fe2754796cd8fba5f229505a23fa08f3546c06" }
```

But it doesn't work yet.
There is some kind of progress, but when i type the command `:lsp-restart` in helixes normal mode i only get a message stating: `Language Server exited`

I don't really know what else i could add or try.
