### ISSUE TITLE
js emit is not supported

### ISSUE THREAD

**Issue by barsbold-coding** [vuejs/language-tools#3889]
# Is there any way to check type? Is it bug or did I do something wrong?
I want to type-check in my CI actions. I created my project with vite-cli.
## CI environment:
```yml
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn type-check
```
## Package.json scripts:
```json
  "scripts": {
    "dev": "vite",
    "build": "run-p type-check \"build-only {@}\" --",
    "preview": "vite preview",
    "test:unit": "vitest",
    "test:e2e": "playwright test",
    "build-only": "vite build",
    "type-check": "vue-tsc --build --force",
    "lint": "eslint \"src/**/*.{ts,vue,js}\"",
    "format": "prettier --write src/",
  },
```
`vue-tsc` version: `^1.8.25`
`vue` version: `^3.3.11`

## TS Config

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "composite": true
  },
  "declaration": true,
  "removeComments": true,
  "skipLibCheck": true,
  "files": ["./src/stores/plugins/*"],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```
`tsconfig.node.json`:
```json
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "include": [
    "vite.config.*",
    "vitest.config.*",
    "cypress.config.*",
    "nightwatch.conf.*",
    "playwright.config.*"
  ],
  "compilerOptions": {
    "composite": true,
    "noEmit": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "types": ["node"]
  }
}
```

## Error
When I execute `yarn type-check`, It gives following error:
```
$ vue-tsc --build --force
js emit is not supported

[path to my project]/node_modules/vue-tsc/bin/vue-tsc.js:68
                        throw err;
                        ^
js emit is not supported
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.11.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
